### ISSUE TITLE
Debian compile/install: FAIL

### ISSUE THREAD

**Issue by Morketh** [Pingus/pingus#148]
so im running a Debian variation (Kali Linux) i grabbed a copy of the git repo and ran a compile using the instructions in the INSTALL.unix file it fails to compile i have variffied all dependiancies are installed:

``` bash
In Ubuntu you can install everything by typing:

 % sudo apt-get install \
     g++ \
     libsdl1.2-dev \
     libsdl-mixer1.2-dev \
     libsdl-image1.2-dev \
     libboost-dev \
     libboost-signals-dev \
     libpng12-dev \
     scons
```

I should probably note this is NOT ubuntu how ever apt-get is the way Kali is able install packages as this is a debian variation.

``` bash
root@kali:~/SOURCE/pingus# make
mkdir -p build
scons src
scons: Reading SConscript files ...
Checking for C++ header file boost/signals2.hpp... yes
Checking for pkg-config...(cached) /usr/bin/pkg-config
Checking for sdl-config...(cached) /usr/bin/sdl-config
Checking for SDL_image...ok
Checking for SDL_mixer...ok
Check how to call iconv...use ''
Checking for C library iconv... no
Reports:
  * OpenGL support: enabled
  * Linux evdev support: ok
  * Wiimote support: disabled
  * XInput support: disabled

scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build/src
g++ -o build/src/editor/action_properties.o -c -O2 -s -std=c++0x -isystem/usr/include/libpng12 -isystem/usr/include/SDL -DVERSION="\"0.7.6\"" -DHAVE_OPENGL=1 -DHAVE_LINUXEVDEV=1 -D_GNU_SOURCE=1 -D_REENTRANT -DHAVE_ICONV_CONST -DICONV_CONST= -Ibuild/src -Isrc -Ibuild -I. -Ibuild/src -Isrc -Ibuild/external/tinygettext/include -Iexternal/tinygettext/include -Ibuild/external/logmich/include -Iexternal/logmich/include src/editor/action_properties.cpp
g++ -o build/src/editor/button.o -c -O2 -s -std=c++0x -isystem/usr/include/libpng12 -isystem/usr/include/SDL -DVERSION="\"0.7.6\"" -DHAVE_OPENGL=1 -DHAVE_LINUXEVDEV=1 -D_GNU_SOURCE=1 -D_REENTRANT -DHAVE_ICONV_CONST -DICONV_CONST= -Ibuild/src -Isrc -Ibuild -I. -Ibuild/src -Isrc -Ibuild/external/tinygettext/include -Iexternal/tinygettext/include -Ibuild/external/logmich/include -Iexternal/logmich/include src/editor/button.cpp
g++ -o build/src/editor/checkbox.o -c -O2 -s -std=c++0x -isystem/usr/include/libpng12 -isystem/usr/include/SDL -DVERSION="\"0.7.6\"" -DHAVE_OPENGL=1 -DHAVE_LINUXEVDEV=1 -D_GNU_SOURCE=1 -D_REENTRANT -DHAVE_ICONV_CONST -DICONV_CONST= -Ibuild/src -Isrc -Ibuild -I. -Ibuild/src -Isrc -Ibuild/external/tinygettext/include -Iexternal/tinygettext/include -Ibuild/external/logmich/include -Iexternal/logmich/include src/editor/checkbox.cpp
g++ -o build/src/editor/combobox.o -c -O2 -s -std=c++0x -isystem/usr/include/libpng12 -isystem/usr/include/SDL -DVERSION="\"0.7.6\"" -DHAVE_OPENGL=1 -DHAVE_LINUXEVDEV=1 -D_GNU_SOURCE=1 -D_REENTRANT -DHAVE_ICONV_CONST -DICONV_CONST= -Ibuild/src -Isrc -Ibuild -I. -Ibuild/src -Isrc -Ibuild/external/tinygettext/include -Iexternal/tinygettext/include -Ibuild/external/logmich/include -Iexternal/logmich/include src/editor/combobox.cpp
g++ -o build/src/editor/editor_level.o -c -O2 -s -std=c++0x -isystem/usr/include/libpng12 -isystem/usr/include/SDL -DVERSION="\"0.7.6\"" -DHAVE_OPENGL=1 -DHAVE_LINUXEVDEV=1 -D_GNU_SOURCE=1 -D_REENTRANT -DHAVE_ICONV_CONST -DICONV_CONST= -Ibuild/src -Isrc -Ibuild -I. -Ibuild/src -Isrc -Ibuild/external/tinygettext/include -Iexternal/tinygettext/include -Ibuild/external/logmich/include -Iexternal/logmich/include src/editor/editor_level.cpp
In file included from src/editor/editor_level.cpp:28:0:
src/util/log.hpp:20:27: fatal error: logmich/log.hpp: No such file or directory
compilation terminated.
scons: *** [build/src/editor/editor_level.o] Error 1
scons: building terminated because of errors.
make: *** [build/pingus] Error 2
```

I also dug through my package manager and found pingus i ran the install through there it seemed to install ok gave me no errors how ever when trying to run the application i recive this error:

```
Could not launch 'Pingus'
Failed to execute child process "pingus" (No such file or directory)
```

Normaly any other ubuntu instructions work with installing/compiling software in kali. in the error report (above) i noticed that the C Library iconv is not found not sure if this is the cause of the problem, however atempting to locate install instructions for the missing library is elusive. I will continue to search for instructions on that and if the problem persissts i will post back here with updated results

**Comment by Morketh** [comment]
well looking closer at the error report it seems to me that the file logmich/log.hpp is not installed or avalible on my system in the defualt location for the linker/compiler to find
[log.hpp Line#20](https://github.com/Pingus/pingus/blob/master/src/util/log.hpp#L20)
doing a fairly quick google seach resulted in finding the logmich/logmich repo located [here](https://github.com/logmich/logmich)
not yet sure how to get pingus to locate or find it with out tweaking a log.hpp (i just might have to do that to get it to run)

**Comment by Morketh** [comment]
Ok i have identified the issue:
the INSTALL instructions are really not clear as to how to clone the repo
running:
``` bash
git submodule init
# and then 
git submodule update
```
will clone the submodules into there proper directories. i think this should be noted in the INSTALL files so that people will have that information as others may not be willing to hunt down answers them selves
re running the compile and waiting for results this issue might be solved

**Comment by Morketh** [comment]
Well this is a new one
```bash
root@kali:~/SOURCE/pingus/build# ./pingus 
Welcome to Pingus 0.7.6!
========================
userdir:                 /root/.config/pingus/
datadir:                 data
language:                English (en)
sound support:           enabled
music support:           enabled
fullscreen:              disabled

[WARN src/util/system.cpp:200] System::opendir(): data/images: No such file or directory
Pingus: Standard exception caught!:
Parser problem: Couldn't open file 'data/images/fonts/chalk-40px.font'.
```
well im at a loss here as to whats really going on with it

**Comment by bugdebugger** [comment]
You need to either run the `pingus` executable from the top of your source tree (`make` created a symbolic link there) or use the `--datadir=` commandline switch. The install instructions on running pingus after compilation are slightly incorrect. I put a pull request #149 to fix these issues in the install instructions

    root@kali:~/SOURCE/pingus# ./pingus

or

    root@kali:~/SOURCE/pingus/build# ./pingus --datadir=../data

**Comment by Morketh** [comment]
i think a note should also be made some where in the instuctions about the git modules
```
git submodule init
# and then 
git submodule update
```
this was not really clear and i had to make a google search to get those commands when the compile failled the first time around

**Comment by MarcinWieczorek** [comment]
Shouldn't this be closed by now?
