### ISSUE TITLE
Pingus should use new Boost Headers

### ISSUE THREAD

**Issue by eyoung100** [Pingus/pingus#162]
Gentoo reports Warning: 
    In file Included from <path>:
    /usr/include/boost/signal.hpp:17:4: warning: #warning "Boost.Signals is no longer being maintained     and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define     BOOST_SIGNALS_NO_DEPRECATION_WARNING." [-Wcpp]
     #  warning                  "Boost.Signals is no longer being maintained and is now deprecated. Please     switch to Boost.Signals2. To disable this warning message, define     BOOST_SIGNALS_NO_DEPRECATION_WARNING."

Please do the "right fix", ie don't just disable the warning.

**Comment by Grumbel** [comment]
Fixed in fef8cf6512fa4aa09e87643c22ef66de9ec7bb41
