### ISSUE TITLE
editor: Play level penguins display is mangled

### ISSUE THREAD

**Issue by lorenzosu** [Pingus/pingus#170]
When trying to play an edited level the penguins are "mangled" in that it looks as if they left a 'trace' as in the screenshot. Also the edited parts are also displayed.
Compiled from git on Fedora 23
![screenshot_2016-02-14_15-40-04](https://cloud.githubusercontent.com/assets/463937/13034273/5e66f338-d331-11e5-836b-2457ce4de415.png)

**Comment by Grumbel** [comment]
That is "normal", you have to manually add a background image otherwise the screen doesn't get cleared. I should probably add some auto-detection for missing backgrounds and clear the screen in those cases.

**Comment by lorenzosu** [comment]
Than you for the pointer! Wasn't aware of the detail. Yes maybe detecting a missing background or having a default single-colour one might be useful.
