### ISSUE TITLE
Tag release 0.7.7

### ISSUE THREAD

**Issue by akien-mga** [Pingus/pingus#172]
I see that you have a release-0.7.7 branch, but no corresponding tag: https://github.com/Pingus/pingus/tree/release-0.7.7

Is this branch a WIP for 0.7.7, or can it be considered the stable release? If the latter, could you make a git tag out of it so that it appears here: https://github.com/Pingus/pingus/releases ? (typically `v0.7.7` to be consistent with previous tags).

**Comment by Grumbel** [comment]
The 0.7.7 branch is a WIP that uses SDL1, master is on SDL2. Originally I planned to cleanup and release 0.7.7 at some point, as the SDL2 one still has issue, but I never got around to that. So next release will probably just be 0.8 with SDL2 and the 0.7.7 will be skipped.
